build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
test: native_and_emulated
conda_build:
  pkg_format: '2'
upload_on_branch: main
conda_build_tool: conda-build+conda-libmamba-solver
